# Generated by Django 5.0.1 on 2024-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='carpart_photos/'),
        ),
    ]
