# Generated by Django 5.0.1 on 2024-01-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_carpart_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carpart_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='carpart',
            name='photo',
        ),
        migrations.AddField(
            model_name='carpart',
            name='photos',
            field=models.ManyToManyField(blank=True, to='djangoProject.photo'),
        ),
    ]
